version: "3.8"

services:
  # Database
  mongo-db:
    container_name: database
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME}
    volumes:
      - ./docker/mongo/init.sh:/docker-entrypoint-initdb.d/init.sh

  # Bot
  beetube-bot:
    container_name: beetube
    build: ./
    user: "node"
    command: npm run dev
    working_dir: /home/src/bot
    restart: on-failure
    depends_on:
      - mongo-db
    env_file:
      - ./.env
    links:
      - mongo-db
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/src/bot
